import { useEffect, useState } from "react";
import { BellRing, Check, CirclePlus, MessageCircle, X } from "lucide-react";
import { createNotification, generateDueNotifications, loadNotifications, setNotificationStatus } from "../lib/notifications";
const types = [["confirmation", "تأكيد موعد"], ["appointment_reminder", "تذكير موعد"], ["post_session", "متابعة بعد الجلسة"], ["outstanding", "تذكير ذمة"], ["package_expiry", "تنبيه انتهاء بكج"]]; const labels = Object.fromEntries(types);
function localValue() { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); }
export function NotificationsPage({ patients, refreshKey, onOpenPatient }) {
  const [rows, setRows] = useState([]); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  async function refresh() { try { setRows(await loadNotifications()); setError(""); } catch (loadError) { setError(loadError.message); } }
  useEffect(() => { refresh(); }, [refreshKey]);
  async function markSent(item) { const phone = String(item.patient?.phone || "").replace(/\D/g, ""); if (phone) window.open(`https://wa.me/${phone}?text=${encodeURIComponent(item.message)}`, "_blank", "noopener,noreferrer"); try { await setNotificationStatus(item.id, "sent"); await refresh(); } catch (actionError) { setError(actionError.message); } }
  async function generate() { try { const count = await generateDueNotifications(); await refresh(); setError(count ? "" : "لا توجد تنبيهات جديدة مستحقة الآن"); } catch (actionError) { setError(actionError.message); } }
  return <section className="operations-page"><header className="page-heading"><div><small>WhatsApp وقائمة الإرسال</small><h2><BellRing size={25} />واتساب والتنبيهات</h2><p>تأكيدات المواعيد، التذكيرات، ما بعد الجلسة، الذمم والباقات.</p></div><div className="finance-actions"><button className="secondary-button" onClick={generate}><BellRing size={17} />توليد المستحق</button><button className="primary-button" onClick={() => setOpen(true)}><CirclePlus size={18} />رسالة جديدة</button></div></header><div className="operations-metrics"><article><span>بانتظار الإرسال</span><strong>{rows.filter((item) => item.status === "pending").length}</strong></article><article><span>تم الإرسال</span><strong>{rows.filter((item) => item.status === "sent").length}</strong></article><article><span>مستحقة الآن</span><strong>{rows.filter((item) => item.status === "pending" && new Date(item.scheduled_for) <= new Date()).length}</strong></article></div>{error && <div className="error-box">{error}</div>}<div className="notification-list">{rows.map((item) => <article key={item.id} className={item.status}><button onClick={() => onOpenPatient(item.patient?.id)}><strong>{item.patient?.full_name}</strong><small>ملف #{item.patient?.file_no} · {labels[item.notification_type]}</small></button><p>{item.message}</p><time>{new Date(item.scheduled_for).toLocaleString("ar-JO")}</time>{item.status === "pending" ? <button className="whatsapp-send" onClick={() => markSent(item)}><MessageCircle size={17} />فتح وإرسال</button> : <span className="sent-state"><Check size={16} />تم الإرسال</span>}</article>)}{!rows.length && <p className="empty-line">لا توجد رسائل مجدولة.</p>}</div>{open && <NotificationDialog patients={patients} onClose={() => setOpen(false)} onSaved={async () => { setOpen(false); await refresh(); }} />}</section>;
}
function NotificationDialog({ patients, onClose, onSaved }) {
  const [form, setForm] = useState({ patientId: patients[0]?.id || "", type: "confirmation", message: "", scheduledFor: localValue() }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  function applyTemplate(type) { const name = patients.find((item) => item.id === form.patientId)?.full_name || ""; const messages = { confirmation: `مرحبًا ${name}، نرجو تأكيد موعدك لدى Casanova Laser Clinic 🌷`, appointment_reminder: `مرحبًا ${name}، تذكير لطيف بموعدك القادم لدى Casanova Laser Clinic 🌷`, post_session: `مرحبًا ${name}، كيف كانت حالتك بعد الجلسة؟ نحن جاهزون لأي استفسار 🌷`, outstanding: `مرحبًا ${name}، نذكّرك بلطف بوجود رصيد مستحق على ملفك. شكرًا لك 🌷`, package_expiry: `مرحبًا ${name}، البكج الخاص بك قريب من الانتهاء. تواصلي معنا لترتيب الجلسات المتبقية 🌷` }; setForm((current) => ({ ...current, type, message: messages[type] })); }
  async function submit(event) { event.preventDefault(); setBusy(true); try { await createNotification(form); onSaved(); } catch (saveError) { setError(saveError.message); } finally { setBusy(false); } }
  return <div className="modal-backdrop"><section className="operation-dialog"><header><h2>جدولة رسالة واتساب</h2><button className="icon-button" onClick={onClose}><X /></button></header><form onSubmit={submit}><div className="form-grid"><div className="field"><label>المريضة</label><select value={form.patientId} onChange={(event) => update("patientId", event.target.value)}>{patients.map((patient) => <option key={patient.id} value={patient.id}>#{patient.file_no} — {patient.full_name}</option>)}</select></div><div className="field"><label>نوع الرسالة</label><select value={form.type} onChange={(event) => applyTemplate(event.target.value)}>{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="field"><label>موعد الإرسال</label><input type="datetime-local" value={form.scheduledFor} onChange={(event) => update("scheduledFor", event.target.value)} required /></div><div className="field field-wide"><label>نص الرسالة</label><textarea rows="4" value={form.message} onChange={(event) => update("message", event.target.value)} required /></div></div>{error && <div className="error-box">{error}</div>}<footer className="modal-actions"><button className="primary-button" disabled={busy}>حفظ في قائمة الإرسال</button><button type="button" className="secondary-button" onClick={onClose}>إلغاء</button></footer></form></section></div>;
}
