import { useEffect, useMemo, useState } from "react";
import { CirclePlus, Package, Search, X } from "lucide-react";
import { paymentMethods } from "../lib/appointments";
import { createPackage, loadPackages, packageStatuses, updatePackageStatus } from "../lib/packages";

const statusLabels = Object.fromEntries(packageStatuses);
function todayValue() { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 10); }
function money(value) { return `${Number(value || 0).toFixed(2)} د.أ`; }

export function PackagesPage({ patients, services, refreshKey, onOpenPatient, onChanged }) {
  const [packages, setPackages] = useState([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("active"); const [dialogOpen, setDialogOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function refresh() { setLoading(true); try { setPackages(await loadPackages()); setError(""); } catch (loadError) { setError(loadError?.message || "تعذر تحميل الباقات"); } finally { setLoading(false); } }
  useEffect(() => { refresh(); }, [refreshKey]);
  const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); return packages.filter((item) => (status === "all" || item.status === status) && `${item.patient?.full_name || ""} ${item.name || ""} ${item.service?.name || ""}`.toLowerCase().includes(normalized)); }, [packages, query, status]);
  const active = packages.filter((item) => item.status === "active"); const remaining = active.reduce((sum, item) => sum + Math.max(0, item.total_sessions - item.used_sessions), 0); const balances = packages.reduce((sum, item) => sum + Math.max(0, Number(item.total_price) - Number(item.paid_amount)), 0);
  async function changeStatus(item, nextStatus) { try { const updated = await updatePackageStatus(item.id, nextStatus); setPackages((rows) => rows.map((row) => row.id === item.id ? updated : row)); onChanged?.(); } catch (actionError) { setError(actionError.message); } }
  return <section className="operations-page"><header className="page-heading"><div><small>إدارة الجلسات المسبقة</small><h2><Package size={25} />الباقات</h2><p>متابعة الجلسات المستخدمة والمتبقية والدفعات وصلاحية كل بكج.</p></div><button className="primary-button" onClick={() => setDialogOpen(true)}><CirclePlus size={18} />بكج جديد</button></header><div className="operations-metrics"><article><span>الباقات النشطة</span><strong>{active.length}</strong></article><article><span>الجلسات المتبقية</span><strong>{remaining}</strong></article><article className={balances ? "danger" : ""}><span>أرصدة الباقات</span><strong>{money(balances)}</strong></article></div><div className="operations-toolbar"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="بحث بالمريضة أو اسم البكج" /></label><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">كل الحالات</option>{packageStatuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{error && <div className="error-box">{error}</div>}{loading ? <div className="calendar-loading">جاري تحميل الباقات...</div> : <div className="package-grid">{filtered.length ? filtered.map((item) => <PackageCard key={item.id} item={item} onOpenPatient={onOpenPatient} onStatus={changeStatus} />) : <p className="empty-line">لا توجد باقات مطابقة.</p>}</div>}{dialogOpen && <PackageDialog patients={patients} services={services} onClose={() => setDialogOpen(false)} onSaved={async () => { setDialogOpen(false); await refresh(); onChanged?.(); }} />}</section>;
}

function PackageCard({ item, onOpenPatient, onStatus }) { const remaining = Math.max(0, item.total_sessions - item.used_sessions); const progress = Math.min(100, Math.round((item.used_sessions / item.total_sessions) * 100)); return <article className={`package-card ${item.status}`}><header><span><Package size={20} /></span><div><h3>{item.name}</h3><button onClick={() => onOpenPatient(item.patient?.id)}>{item.patient?.full_name || "—"} · ملف #{item.patient?.file_no || "—"}</button></div><em>{statusLabels[item.status] || item.status}</em></header><p>{item.service?.name || "باقة عامة"}</p><div className="package-progress"><div><span style={{ width: `${progress}%` }} /></div><strong>{remaining} من {item.total_sessions} جلسة متبقية</strong></div><div className="package-finance"><span>السعر <strong>{money(item.total_price)}</strong></span><span>المدفوع <strong>{money(item.paid_amount)}</strong></span><span>المتبقي <strong>{money(Number(item.total_price) - Number(item.paid_amount))}</strong></span></div><footer><span>{item.expires_on ? `ينتهي ${item.expires_on}` : "بدون تاريخ انتهاء"}</span>{item.status === "active" ? <button onClick={() => onStatus(item, "cancelled")}>إلغاء البكج</button> : item.status === "cancelled" ? <button onClick={() => onStatus(item, "active")}>إعادة التفعيل</button> : null}</footer></article>; }

function PackageDialog({ patients, services, onClose, onSaved }) {
  const [form, setForm] = useState({ patientId: patients[0]?.id || "", serviceId: "", name: "", totalSessions: "6", totalPrice: "0", paidAmount: "0", startsOn: todayValue(), expiresOn: "", notes: "", paymentMethod: "cash" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  function update(key, value) { setForm((current) => ({ ...current, [key]: value })); }
  function selectService(serviceId) { const service = services.find((item) => item.id === serviceId); setForm((current) => ({ ...current, serviceId, name: current.name || (service ? `بكج ${service.name}` : ""), totalSessions: String(service?.sessions_default || current.totalSessions), totalPrice: String(service ? Number(service.price || 0) * Number(service.sessions_default || 1) : current.totalPrice) })); }
  async function submit(event) { event.preventDefault(); setBusy(true); setError(""); try { if (Number(form.paidAmount) > Number(form.totalPrice)) throw new Error("المدفوع لا يمكن أن يتجاوز سعر البكج"); await createPackage(form); onSaved(); } catch (saveError) { setError(saveError?.message || "تعذر إنشاء البكج"); } finally { setBusy(false); } }
  return <div className="modal-backdrop"><section className="operation-dialog" role="dialog" aria-modal="true"><header><div><h2>إنشاء بكج جديد</h2><p>الدفعة الأولى تُسجل تلقائيًا في الحسابات.</p></div><button className="icon-button" onClick={onClose}><X size={20} /></button></header><form onSubmit={submit}><div className="form-grid"><div className="field"><label>المريضة</label><select value={form.patientId} onChange={(event) => update("patientId", event.target.value)} required>{patients.map((patient) => <option key={patient.id} value={patient.id}>#{patient.file_no} — {patient.full_name}</option>)}</select></div><div className="field"><label>الخدمة</label><select value={form.serviceId} onChange={(event) => selectService(event.target.value)}><option value="">بكج عام</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></div><div className="field"><label>اسم البكج</label><input value={form.name} onChange={(event) => update("name", event.target.value)} required /></div><div className="field"><label>عدد الجلسات</label><input type="number" min="1" value={form.totalSessions} onChange={(event) => update("totalSessions", event.target.value)} required /></div><div className="field"><label>السعر الإجمالي</label><input type="number" min="0" step=".01" value={form.totalPrice} onChange={(event) => update("totalPrice", event.target.value)} required /></div><div className="field"><label>الدفعة الأولى</label><input type="number" min="0" step=".01" max={form.totalPrice || undefined} value={form.paidAmount} onChange={(event) => update("paidAmount", event.target.value)} /></div><div className="field"><label>طريقة الدفع</label><select value={form.paymentMethod} onChange={(event) => update("paymentMethod", event.target.value)}>{paymentMethods.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="field"><label>تاريخ البدء</label><input type="date" value={form.startsOn} onChange={(event) => update("startsOn", event.target.value)} required /></div><div className="field"><label>تاريخ الانتهاء</label><input type="date" min={form.startsOn} value={form.expiresOn} onChange={(event) => update("expiresOn", event.target.value)} /></div><div className="field field-wide"><label>ملاحظات</label><textarea rows="3" value={form.notes} onChange={(event) => update("notes", event.target.value)} /></div></div>{error && <div className="error-box">{error}</div>}<footer className="modal-actions"><button className="primary-button" disabled={busy}>{busy ? "جاري الإنشاء..." : "إنشاء البكج"}</button><button type="button" className="secondary-button" onClick={onClose}>إلغاء</button></footer></form></section></div>;
}
